# Generated by Django 5.0.4 on 2024-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='lecturer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
