# Generated by Django 5.0.4 on 2024-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department_user_lecturer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
