# Generated by Django 5.0.4 on 2024-05-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupModel',
            new_name='Group',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('album_number', models.IntegerField(default=561071, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.group')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
