# Generated by Django 5.0.4 on 2024-05-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_student_album_number_alter_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_number',
        ),
        migrations.AddField(
            model_name='group',
            name='full_name',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='album_number',
            field=models.IntegerField(default=823483, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
