# Generated by Django 5.0.4 on 2024-05-12 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_student_active_alter_student_album_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledLecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('remote', 'Remote'), ('stationary', 'Stationary')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('dateStart', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.group')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.lecture')),
            ],
        ),
    ]
