# Generated by Django 5.0.4 on 2024-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_rename_lecture_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledlecture',
            options={'ordering': ['dateStart']},
        ),
        migrations.RemoveField(
            model_name='scheduledlecture',
            name='active',
        ),
        migrations.AddField(
            model_name='scheduledlecture',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
