# Generated by Django 5.0.4 on 2024-06-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read']},
        ),
    ]
